services:
  api:
    build: .
    container_name: minha-api-nest
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1350"